"""Bulk-reserved handles — high-value names protected at signup.

Imported by ``handles.py``. Boot-time sync (``sync_reserved``) upserts these
into ``reserved_handles``. Released entries are NEVER re-added — if an admin
frees @KLOPP, this module won't claw it back.

Lists are organised by club/category so adding a new signing is a one-line
change. Naming convention: ``A-Z``, ``0-9``, ``_`` only, 3–20 chars, never
starting with a digit. Common-English-word surnames (KING, WOOD, COLE,
BELL...) deliberately omitted — they'd cause too many false-positive blocks.
"""
from __future__ import annotations

# ── Premier League 2025/26 squads ──────────────────────────────────────────
# Sourced from current first-team rosters. Includes nicknames where well-known
# (e.g. KDB, VVD, TAA). Loan moves and academy debutants tracked too.

PL_SQUADS: dict[str, list[str]] = {
    "ARSENAL": [
        "SAKA", "BUKAYO_SAKA", "ODEGAARD", "MARTIN_ODEGAARD", "RICE",
        "DECLAN_RICE", "MARTINELLI", "GABRIEL_MARTINELLI", "GABRIEL_JESUS",
        "JESUS", "GABRIEL_MAGALHAES", "BEN_WHITE", "BENWHITE", "ZINCHENKO",
        "TROSSARD", "HAVERTZ", "KAI_HAVERTZ", "RAYA", "DAVID_RAYA",
        "TIMBER", "JURRIEN_TIMBER", "PARTEY", "THOMAS_PARTEY", "JORGINHO",
        "CALAFIORI", "RICCARDO_CALAFIORI", "MERINO", "MIKEL_MERINO",
        "NWANERI", "ETHAN_NWANERI", "LEWIS_SKELLY", "MYLES_LEWIS_SKELLY",
        "STERLING", "RAHEEM_STERLING", "TOMIYASU", "TAKEHIRO_TOMIYASU",
        "GYOKERES", "VIKTOR_GYOKERES",
    ],
    "ASTON_VILLA": [
        "WATKINS", "OLLIE_WATKINS", "MCGINN", "JOHN_MCGINN", "RAMSEY",
        "JACOB_RAMSEY", "ROGERS", "MORGAN_ROGERS", "EMI_MARTINEZ",
        "DIBU", "DIBU_MARTINEZ", "EMILIANO_MARTINEZ", "DIGNE", "LUCAS_DIGNE",
        "KONSA", "EZRI_KONSA", "PAU_TORRES", "BAILEY", "LEON_BAILEY",
        "MAATSEN", "IAN_MAATSEN", "DURAN", "JHON_DURAN", "TIELEMANS",
        "YOURI_TIELEMANS", "ASENSIO", "MARCO_ASENSIO", "BUENDIA",
        "EMI_BUENDIA", "BARKLEY", "ROSS_BARKLEY", "ONANA_AVFC",
        "AMADOU_ONANA", "MALEN", "DONYELL_MALEN", "BOGARDE", "LAMARE_BOGARDE",
        "KAMARA", "BOUBACAR_KAMARA", "GUESSAND",
    ],
    "BOURNEMOUTH": [
        "KLUIVERT", "JUSTIN_KLUIVERT", "EVANILSON", "SEMENYO",
        "ANTOINE_SEMENYO", "TAVERNIER", "MARCUS_TAVERNIER", "BROOKS",
        "DAVID_BROOKS", "ARRIZABALAGA", "KEPA", "PETROVIC", "DJORDJE_PETROVIC",
        "ZABARNYI", "ILLIA_ZABARNYI", "HUIJSEN", "DEAN_HUIJSEN", "KERKEZ",
        "MILOS_KERKEZ", "ADAMS", "TYLER_ADAMS", "CHRISTIE", "RYAN_CHRISTIE",
        "OUATTARA", "DANGO_OUATTARA", "SCOTT_BOURNEMOUTH", "ALEX_SCOTT",
        "UNAL", "ENES_UNAL", "DOAK", "BEN_DOAK", "SOLANKE",
    ],
    "BRENTFORD": [
        "MBEUMO", "BRYAN_MBEUMO", "WISSA", "YOANE_WISSA", "DAMSGAARD",
        "MIKKEL_DAMSGAARD", "JANELT", "VITALY_JANELT", "JENSEN",
        "MATHIAS_JENSEN", "NORGAARD", "CHRISTIAN_NORGAARD", "FLEKKEN",
        "MARK_FLEKKEN", "COLLINS", "NATHAN_COLLINS", "PINNOCK", "ETHAN_PINNOCK",
        "AJER", "KRISTOFFER_AJER", "VAN_DEN_BERG", "SCHADE", "KEVIN_SCHADE",
        "LEWIS_POTTER", "YARMOLYUK", "YEGOR_YARMOLYUK", "THIAGO",
    ],
    "BRIGHTON": [
        "MITOMA", "KAORU_MITOMA", "WELBECK", "DANNY_WELBECK", "JOAO_PEDRO",
        "PEDRO_BRIGHTON", "ENCISO", "JULIO_ENCISO", "ESTUPINAN",
        "PERVIS_ESTUPINAN", "ESTUPINAN", "VAN_HECKE", "JAN_PAUL_VAN_HECKE",
        "VERBRUGGEN", "BART_VERBRUGGEN", "GROSS", "PASCAL_GROSS", "BALEBA",
        "CARLOS_BALEBA", "MINTEH", "YANKUBA_MINTEH", "MUHEIM", "GRUDA",
        "BRAJAN_GRUDA", "PEDRO_HINCAPIE",
    ],
    "BURNLEY": [
        "FOSTER", "LYLE_FOSTER", "ANTHONY", "JAIDON_ANTHONY", "TRAFFORD",
        "JAMES_TRAFFORD", "EKDAL", "BRUUN_LARSEN", "JESPER_LARSEN",
        "BRUUN", "ESTEVE", "MAXIME_ESTEVE", "DELCROIX", "AMEEN_AL_DAKHIL",
        "EKDAL", "ALBERTO_BENITEZ", "FOFANA", "DAVID_DATRO_FOFANA",
        "MASSENGO", "HANNIBAL", "MEJBRI", "BERGE", "SANDER_BERGE",
    ],
    "CHELSEA": [
        "PALMER", "COLE_PALMER", "JACKSON", "NICOLAS_JACKSON", "ENZO",
        "ENZO_FERNANDEZ", "CAICEDO", "MOISES_CAICEDO", "FOFANA_CHELSEA",
        "WESLEY_FOFANA", "COLWILL", "LEVI_COLWILL", "JAMES_CHELSEA",
        "REECE_JAMES", "CUCURELLA", "MARC_CUCURELLA", "MUDRYK", "MYKHAILO_MUDRYK",
        "STERLING_CHEL", "MADUEKE", "NONI_MADUEKE", "DEWSBURY_HALL",
        "KIERNAN_DEWSBURY_HALL", "GUSTO", "MALO_GUSTO", "LAVIA", "ROMEO_LAVIA",
        "JORGENSEN", "FILIP_JORGENSEN", "DELAP", "LIAM_DELAP", "GITTENS",
        "JAMIE_GITTENS", "GUIU", "MARC_GUIU", "ESTEVAO", "JOAO_FELIX",
        "PEDRO_NETO_CHEL", "NETO", "NKUNKU", "CHRISTOPHER_NKUNKU",
    ],
    "CRYSTAL_PALACE": [
        "EZE", "EBERECHI_EZE", "OLISE_EX", "MATETA", "JEAN_PHILIPPE_MATETA",
        "GUEHI", "MARC_GUEHI", "HENDERSON", "DEAN_HENDERSON", "MITCHELL",
        "TYRICK_MITCHELL", "RICHARDS_PAL", "CHRIS_RICHARDS", "LERMA",
        "JEFFERSON_LERMA", "MUNOZ", "DANIEL_MUNOZ", "WHARTON", "ADAM_WHARTON",
        "DOUCOURE", "CHEICK_DOUCOURE", "SARR", "ISMAILA_SARR", "EDOUARD",
        "ODSONNE_EDOUARD", "KAMADA", "DAICHI_KAMADA", "NKETIAH", "EDDIE_NKETIAH",
    ],
    "EVERTON": [
        "PICKFORD", "JORDAN_PICKFORD", "DOUCOURE_EVE", "ABDOULAYE_DOUCOURE",
        "BRANTHWAITE", "JARRAD_BRANTHWAITE", "TARKOWSKI", "JAMES_TARKOWSKI",
        "GUEYE", "IDRISSA_GUEYE", "GARNER", "JAMES_GARNER", "MCNEIL",
        "DWIGHT_MCNEIL", "BETO", "NDIAYE", "ILIMAN_NDIAYE", "CALVERT_LEWIN",
        "DOMINIC_CALVERT_LEWIN", "DCL", "GROUNDS", "LINDSTROM", "JESPER_LINDSTROM",
        "ALCARAZ", "CARLOS_ALCARAZ", "HARRISON", "JACK_HARRISON", "ENDO",
    ],
    "FULHAM": [
        "MUNIZ", "RODRIGO_MUNIZ", "WILSON_FUL", "HARRY_WILSON", "TRAORE",
        "ADAMA_TRAORE", "PEREIRA_FUL", "ANDREAS_PEREIRA", "IWOBI", "ALEX_IWOBI",
        "BERGE_FUL", "SMITH_ROWE", "EMILE_SMITH_ROWE", "ESR", "LENO",
        "BERND_LENO", "ROBINSON_FUL", "ANTONEE_ROBINSON", "TETE", "KENNY_TETE",
        "BASSEY", "CALVIN_BASSEY", "KUSI_ASARE", "DIOP", "ISSA_DIOP", "JIMENEZ",
        "RAUL_JIMENEZ", "JOACHIM_ANDERSEN", "ANDERSEN_FUL", "JOSE_PALHINHA",
        "PALHINHA",
    ],
    "LEEDS": [
        "JAMES_LEEDS", "DANIEL_JAMES", "BAMFORD", "PATRICK_BAMFORD",
        "JOSEPH_LEEDS", "ROCA", "MARC_ROCA", "GNONTO", "WILLY_GNONTO",
        "FIRPO", "JUNIOR_FIRPO", "AARONSON", "BRENDEN_AARONSON", "DARLOW",
        "KARL_DARLOW", "LANGLEY", "RUTTER",
    ],
    "LIVERPOOL": [
        "SALAH", "MO_SALAH", "MOHAMED_SALAH", "VAN_DIJK", "VVD", "VIRGIL",
        "TRENT", "TAA", "TRENT_ALEXANDER_ARNOLD", "MAC_ALLISTER",
        "ALEXIS_MAC_ALLISTER", "SZOBOSZLAI", "DOMINIK_SZOBOSZLAI", "GAKPO",
        "COD_GAKPO", "DIAZ_LIV", "LUIS_DIAZ", "DIOGO_JOTA", "JOTA",
        "ALISSON", "ALISSON_BECKER", "KELLEHER", "CAOIMHIN_KELLEHER",
        "ROBERTSON", "ANDY_ROBERTSON", "KONATE", "IBRAHIMA_KONATE", "QUANSAH",
        "JARELL_QUANSAH", "ENDO_LIV", "WATARU_ENDO", "ELLIOTT", "HARVEY_ELLIOTT",
        "JONES_LIV", "CURTIS_JONES", "GRAVENBERCH", "RYAN_GRAVENBERCH",
        "FRIMPONG", "JEREMIE_FRIMPONG", "WIRTZ", "FLORIAN_WIRTZ", "EKITIKE",
        "HUGO_EKITIKE", "KERKEZ_LIV", "MAMARDASHVILI",
    ],
    "MAN_CITY": [
        "HAALAND", "ERLING_HAALAND", "DEBRUYNE", "KEVIN_DEBRUYNE", "KDB",
        "FODEN", "PHIL_FODEN", "BERNARDO", "BERNARDO_SILVA", "RODRIGO",
        "RODRI", "GVARDIOL", "JOSKO_GVARDIOL", "AKE", "NATHAN_AKE", "DIAS",
        "RUBEN_DIAS", "STONES", "JOHN_STONES", "WALKER", "KYLE_WALKER",
        "ORTEGA", "STEFAN_ORTEGA", "EDERSON", "DOKU", "JEREMY_DOKU", "GREALISH",
        "JACK_GREALISH", "MARMOUSH", "OMAR_MARMOUSH", "REIJNDERS", "TIJJANI_REIJNDERS",
        "KOVACIC", "MATEO_KOVACIC", "GUNDOGAN", "ILKAY_GUNDOGAN", "NUNES",
        "MATHEUS_NUNES", "SAVINHO", "BOBB", "OSCAR_BOBB", "ECHEVERRI",
        "KHUSANOV", "AIT_NOURI_MCI",
    ],
    "MAN_UNITED": [
        "BRUNO_MUFC", "BRUNO_FERNANDES", "FERNANDES", "RASHFORD", "MARCUS_RASHFORD",
        "GARNACHO", "ALEJANDRO_GARNACHO", "MAINOO", "KOBBIE_MAINOO", "ONANA",
        "ANDRE_ONANA", "MAGUIRE", "HARRY_MAGUIRE", "MARTINEZ_MUFC", "LISANDRO",
        "LICHA", "DALOT", "DIOGO_DALOT", "MAZRAOUI", "NOUSSAIR_MAZRAOUI",
        "DE_LIGT", "MATTHIJS_DE_LIGT", "UGARTE", "MANUEL_UGARTE", "EVANS",
        "JONNY_EVANS", "ANTONY", "ZIRKZEE", "JOSHUA_ZIRKZEE", "MAZARA",
        "DIALLO", "AMAD_DIALLO", "EJN", "EJNALDS", "AMAD", "HOJLUND",
        "RASMUS_HOJLUND", "BAYINDIR", "ALTAY_BAYINDIR", "LAMMENS",
        "CUNHA_MUFC", "MATHEUS_CUNHA", "MBEUMO_MUFC", "DORGU", "PATRICK_DORGU",
        "YORO", "LENY_YORO", "CASEMIRO",
    ],
    "NEWCASTLE": [
        "ISAK", "ALEXANDER_ISAK", "GORDON", "ANTHONY_GORDON", "BRUNO_NEW",
        "BRUNO_GUIMARAES", "GUIMARAES", "BARNES", "HARVEY_BARNES", "MURPHY",
        "JACOB_MURPHY", "POPE", "NICK_POPE", "DUBRAVKA", "MARTIN_DUBRAVKA",
        "TRIPPIER", "KIERAN_TRIPPIER", "BOTMAN", "SVEN_BOTMAN", "SCHAR",
        "FABIAN_SCHAR", "BURN", "DAN_BURN", "TONALI", "SANDRO_TONALI",
        "JOELINTON", "ALMIRON", "MIGUEL_ALMIRON", "WILLOCK", "JOE_WILLOCK",
        "RAMSDALE", "AARON_RAMSDALE", "HALL_NEW", "LEWIS_HALL", "WOLTEMADE",
        "NICK_WOLTEMADE", "ELANGA", "ANTHONY_ELANGA",
    ],
    "NOTTINGHAM_FOREST": [
        "WOOD_NFFC", "AWONIYI", "TAIWO_AWONIYI", "GIBBS_WHITE", "MORGAN_GIBBS_WHITE",
        "ELANGA_NFFC", "HUDSON_ODOI", "CALLUM_HUDSON_ODOI", "MILENKOVIC",
        "NIKOLA_MILENKOVIC", "MURILLO", "SELS", "MATZ_SELS", "DOMINGUEZ",
        "NICOLAS_DOMINGUEZ", "AINA", "OLA_AINA", "ANDERSON_NFFC",
        "ELLIOT_ANDERSON", "SANGARE", "IBRAHIM_SANGARE", "CHRIS_WOOD",
        "HUTCHINSON", "OMARI_HUTCHINSON",
    ],
    "SUNDERLAND": [
        "MAYENDA", "ELIEZER_MAYENDA", "ROBERTS_SAFC", "PATRICK_ROBERTS",
        "RIGG", "CHRIS_RIGG", "ENZO_LE_FEE", "LE_FEE", "BELLINGHAM_SAFC",
        "JOBE_BELLINGHAM", "JOBE", "MUNDLE",
    ],
    "SPURS": [
        "SON", "HEUNG_MIN_SON", "MADDISON", "JAMES_MADDISON", "RICHARLISON",
        "JOHNSON", "BRENNAN_JOHNSON", "WERNER", "TIMO_WERNER", "ROMERO",
        "CRISTIAN_ROMERO", "VAN_DE_VEN", "MICKY_VAN_DE_VEN", "PORRO",
        "PEDRO_PORRO", "UDOGIE", "DESTINY_UDOGIE", "VICARIO", "GUGLIELMO_VICARIO",
        "BISSOUMA", "YVES_BISSOUMA", "BENTANCUR", "RODRIGO_BENTANCUR", "SARR_THFC",
        "PAPE_MATAR_SARR", "SOLANKE", "DOMINIC_SOLANKE", "GRAY_THFC", "ARCHIE_GRAY",
        "BERGVALL", "LUCAS_BERGVALL", "ODOBERT", "WILSON_ODOBERT", "DRAGUSIN",
        "RADU_DRAGUSIN", "DANSO", "KEVIN_DANSO", "TEL", "MATHYS_TEL",
        "KUDUS", "MOHAMMED_KUDUS", "PALHINHA_THFC",
    ],
    "WEST_HAM": [
        "PAQUETA", "LUCAS_PAQUETA", "BOWEN", "JARROD_BOWEN", "ANTONIO",
        "MICHAIL_ANTONIO", "WARD_PROWSE", "JAMES_WARD_PROWSE", "JWP",
        "AREOLA", "ALPHONSE_AREOLA", "FABIANSKI", "LUKASZ_FABIANSKI",
        "ZOUMA", "KURT_ZOUMA", "KILMAN", "MAX_KILMAN", "EMERSON_PALMIERI",
        "EMERSON_WHU", "MAVROPANOS", "KONSTANTINOS_MAVROPANOS", "RODRIGUEZ_WHU",
        "GUIDO_RODRIGUEZ", "FULLKRUG", "NICLAS_FULLKRUG", "SOUCEK",
        "TOMAS_SOUCEK", "KUDUS_WHU", "WAN_BISSAKA", "AARON_WAN_BISSAKA",
        "AWB", "POTTS",
    ],
    "WOLVES": [
        "CUNHA_WOLV", "AIT_NOURI", "RAYAN_AIT_NOURI", "JOAO_GOMES",
        "GOMES_WOLV", "JOSE_SA", "SARABIA", "PABLO_SARABIA", "DOHERTY",
        "MATT_DOHERTY", "AGBADOU", "EMMANUEL_AGBADOU", "TOTI_GOMES",
        "TOTI", "BUENO", "SANTI_BUENO", "BELLEGARDE", "JEAN_RICNER_BELLEGARDE",
        "RODRIGO_GOMES", "STRAND_LARSEN", "JORGEN_STRAND_LARSEN", "GUEDES",
        "GONCALO_GUEDES", "ANDRE_WOLV", "ANDRE_TRINCAO", "TRINCAO",
    ],
}

# ── Championship 2025/26 (top players + season stars) ──────────────────────
# Lighter coverage — full squad lists would balloon the file. Top ~12 per club
# (managers, captains, top scorers, key signings).

CHAMP_PLAYERS: list[str] = [
    # Birmingham
    "DEMARAI_GRAY", "TOMOKI_IWATA", "JAY_STANSFIELD", "STANSFIELD",
    "PHIL_NEUMANN", "EHEAA",
    # Blackburn
    "TYRHYS_DOLAN", "DOLAN", "SAM_GALLAGHER", "DUNCAN_MCGUCKIN",
    # Bristol City
    "TOMMY_CONWAY", "ANIS_MEHMETI", "JASON_KNIGHT", "GEORGE_TANNER",
    # Burnley (now PL but recent)
    "ANASS_ZAROURY",
    # Cardiff
    "AARON_RAMSEY_CAR", "CALLUM_O_DOWDA", "ANDY_RINOMHOTA", "PERRY_NG",
    # Coventry
    "HAJI_WRIGHT", "VICTOR_TORP", "ELLIS_SIMMS", "JAY_DASILVA",
    # Derby
    "JERRY_YATES", "EBOU_ADAMS", "NATHANIEL_MENDEZ_LAING",
    # Hull City
    "REGAN_SLATER", "JEAN_MICHAEL_SERI",
    # Leeds (PL now)
    "WILLY_GNONTO_LEEDS",
    # Leicester (PL again)
    "MADS_HERMANSEN", "HARRY_WINKS",
    # Luton
    "ELIJAH_ADEBAYO", "CARLTON_MORRIS", "JORDAN_CLARK",
    # Middlesbrough
    "EMMANUEL_LATTE_LATH", "LATTE_LATH", "MORGAN_ROGERS_BORO", "TOMMY_CONWAY_BORO",
    "RAV_VAN_DEN_BERG",
    # Millwall
    "ZIAN_FLEMMING", "RYAN_LEONARD", "ROMAIN_ESSE",
    # Norwich
    "BORJA_SAINZ", "JOSH_SARGENT", "GABRIEL_SARA", "JONATHAN_ROWE",
    "ROWE_NOR", "ANGUS_GUNN",
    # Plymouth
    "MORGAN_WHITTAKER", "RYAN_HARDIE", "LEWIS_GIBSON",
    # Portsmouth
    "COLBY_BISHOP", "PADDY_LANE", "MARLON_PACK",
    # Preston
    "EMIL_RIIS", "MILUTIN_OSMAJIC", "DUANE_HOLMES",
    # QPR
    "LYNDON_DYKES", "ILIAS_CHAIR", "PAUL_SMYTH",
    # Sheffield United
    "GUSTAVO_HAMER", "HAMER", "VINICIUS_SOUZA", "TYRESE_CAMPBELL", "JAMIE_SHACKLETON",
    "OLIVER_ARBLASTER", "KIEFFER_MOORE",
    # Sheffield Wednesday
    "JOSH_WINDASS", "BARRY_BANNAN", "BANNAN", "MICHAEL_SMITH_SWFC",
    # Southampton (PL/Champ flux)
    "ADAM_ARMSTRONG", "CAMERON_ARCHER",
    # Stoke
    "BAE_JUNHO", "JUNHO", "MILLENIC", "WESLEY",
    # Swansea
    "RONALD",
    # Watford
    "VAKOUN_BAYO", "GIORGI_CHAKVETADZE", "EDO_KAYEMBE", "TOM_DELE_BASHIRU",
    # WBA
    "JOSH_MAJA", "TOM_FELLOWS", "MIKEY_JOHNSTON", "CALLUM_STYLES",
]

# ── Scottish Premiership ───────────────────────────────────────────────────

SCOTTISH_PLAYERS: list[str] = [
    # Celtic
    "KYOGO", "KYOGO_FURUHASHI", "MAEDA", "DAIZEN_MAEDA", "REO_HATATE", "HATATE",
    "CALLUM_MCGREGOR", "MCGREGOR_CEL", "MATT_OREILLY", "OREILLY",
    "ARNE_ENGELS", "ADAM_IDAH", "LIAM_SCALES", "CAMERON_CARTER_VICKERS",
    "AUSTON_TRUSTY", "ALISTAIR_JOHNSTON", "GREG_TAYLOR", "NICOLAS_KUHN",
    # Rangers
    "JAMES_TAVERNIER", "TAVERNIER", "CYRIEL_DESSERS", "CONNOR_BARRON",
    "RIDVAN_YILMAZ", "RABBI_MATONDO", "DANILO", "VACLAV_CERNY", "MOHAMED_DIOMANDE",
    "JOHN_SOUTTAR", "ROBIN_PROPPER", "JEFTE",
    # Hearts
    "LAWRENCE_SHANKLAND", "SHANKLAND", "ALAN_FORREST", "JORGE_GRANT",
    "ZANDER_CLARK", "STEPHEN_KINGSLEY",
    # Hibs
    "MARTIN_BOYLE", "BOYLE", "ADAM_LE_FONDRE", "MYKOLA_KUKHAREVYCH",
    # Aberdeen
    "BOJAN_MIOVSKI", "MIOVSKI", "ESTER_SOKLER", "GRAEME_SHINNIE",
    # Other SPL
    "SIMON_MURRAY", "DUNDEE_SCOTT", "LYALL_CAMERON", "STEPHEN_KELLY",
    "ROSS_COUNTY", "JORDAN_WHITE", "BOJAN_KNEZEVIC",
]

# ── La Liga / Serie A / Bundesliga / Ligue 1 — top-tier names ──────────────

EUROPEAN_STARS: list[str] = [
    # Real Madrid
    "VINICIUS", "VINICIUS_JR", "RODRYGO", "BELLINGHAM", "JUDE_BELLINGHAM",
    "MBAPPE", "KYLIAN_MBAPPE", "BRAHIM_DIAZ", "MILITAO", "EDER_MILITAO",
    "RUDIGER", "ANTONIO_RUDIGER", "CAMAVINGA", "EDUARDO_CAMAVINGA", "TCHOUAMENI",
    "AURELIEN_TCHOUAMENI", "VALVERDE", "FEDE_VALVERDE", "COURTOIS",
    "THIBAUT_COURTOIS", "LUNIN", "ENDRICK", "ARDA_GULER",
    # Barcelona
    "LAMINE", "LAMINE_YAMAL", "YAMAL", "PEDRI", "GAVI", "RAPHINHA",
    "LEWANDOWSKI", "ROBERT_LEWANDOWSKI", "TER_STEGEN", "MARC_ANDRE_TER_STEGEN",
    "INAKI_PENA", "ARAUJO", "RONALD_ARAUJO", "KOUNDE", "JULES_KOUNDE",
    "BALDE", "ALEJANDRO_BALDE", "FERMIN", "FERRAN_TORRES", "FRENKIE_DE_JONG",
    "DE_JONG_FCB", "DANI_OLMO", "OLMO",
    # Atletico Madrid
    "GRIEZMANN", "ANTOINE_GRIEZMANN", "JULIAN_ALVAREZ", "ALVAREZ_ATM",
    "OBLAK", "JAN_OBLAK", "RIQUELME",
    # Bayern Munich
    "MUSIALA", "JAMAL_MUSIALA", "KIMMICH", "JOSHUA_KIMMICH", "MUSALA",
    "SANE", "LEROY_SANE", "GORETZKA", "LEON_GORETZKA", "DAVIES",
    "ALPHONSO_DAVIES", "NEUER", "MANUEL_NEUER", "OLISE_BAY", "MICHAEL_OLISE",
    "KANE", "HARRY_KANE", "DIER", "KIM_MIN_JAE", "UPAMECANO", "DAYOT_UPAMECANO",
    "PAVLOVIC", "ALEKSANDAR_PAVLOVIC", "KARL_HEINZ",
    # BVB
    "REUS", "MARCO_REUS", "ADEYEMI", "KAREEM_ADEYEMI", "SCHLOTTERBECK",
    "NICO_SCHLOTTERBECK", "BRANDT", "JULIAN_BRANDT", "GUIRASSY",
    "SERHOU_GUIRASSY", "BEIER", "MAXIMILIAN_BEIER",
    # Leverkusen
    "ALONSO_BAY", "GRANIT_XHAKA", "XHAKA", "WIRTZ_BAY",
    # PSG
    "DEMBELE", "OUSMANE_DEMBELE", "DOUE", "DESIRE_DOUE", "HAKIMI",
    "ACHRAF_HAKIMI", "DONNARUMMA", "GIANLUIGI_DONNARUMMA", "MARQUINHOS",
    "VITINHA", "FABIAN_RUIZ", "ZAIRE_EMERY", "WARREN_ZAIRE_EMERY", "BARCOLA",
    "BRADLEY_BARCOLA",
    # Inter
    "LAUTARO", "LAUTARO_MARTINEZ", "THURAM", "MARCUS_THURAM", "BARELLA",
    "NICOLO_BARELLA", "BASTONI", "ALESSANDRO_BASTONI", "CALHANOGLU",
    "HAKAN_CALHANOGLU", "SOMMER", "YANN_SOMMER",
    # Milan / Juventus / Roma
    "LEAO", "RAFAEL_LEAO", "PULISIC", "CHRISTIAN_PULISIC", "THEO_HERNANDEZ",
    "MAIGNAN", "MIKE_MAIGNAN", "VLAHOVIC", "DUSAN_VLAHOVIC", "YILDIZ",
    "KENAN_YILDIZ", "DYBALA", "PAULO_DYBALA", "PELLEGRINI",
    "LORENZO_PELLEGRINI", "LUKAKU", "ROMELU_LUKAKU", "OSIMHEN", "VICTOR_OSIMHEN",
    "MCTOMINAY", "SCOTT_MCTOMINAY",
    # Other notable
    "MORATA", "ALVARO_MORATA", "ASENSIO_FUL", "DI_MARIA", "ANGEL_DI_MARIA",
]

# ── Football icons / historical greats ────────────────────────────────────

ICONS: list[str] = [
    # Modern legends still relevant
    "MESSI", "LIONEL_MESSI", "RONALDO", "CR7", "CRISTIANO", "CRISTIANO_RONALDO",
    "ZLATAN", "IBRAHIMOVIC", "ZLATAN_IBRAHIMOVIC", "INIESTA", "ANDRES_INIESTA",
    "XAVI", "PIRLO", "ANDREA_PIRLO", "RONALDINHO", "KAKA", "RIVALDO",
    "FIGO", "LUIS_FIGO",
    # English greats
    "BECKHAM", "DAVID_BECKHAM", "SCHOLES", "PAUL_SCHOLES", "GIGGS", "RYAN_GIGGS",
    "GERRARD", "STEVEN_GERRARD", "STEVIE_G", "FRANK_LAMPARD", "CANTONA",
    "ERIC_CANTONA", "ROONEY", "WAYNE_ROONEY", "KEANE_MUFC", "ROY_KEANE",
    "VIEIRA", "PATRICK_VIEIRA", "HENRY", "THIERRY_HENRY", "BERGKAMP",
    "DENNIS_BERGKAMP", "SHEARER", "ALAN_SHEARER", "ZOLA", "GIANFRANCO_ZOLA",
    "DROGBA", "DIDIER_DROGBA", "TERRY", "JOHN_TERRY", "FERDINAND",
    "RIO_FERDINAND", "VIDIC", "NEMANJA_VIDIC", "VAN_NISTELROOY",
    "RUUD_VAN_NISTELROOY", "OWEN", "MICHAEL_OWEN", "BECKENBAUER", "PUSKAS",
    "EUSEBIO", "GASCOIGNE", "PAUL_GASCOIGNE", "GAZZA", "LINEKER_PLAY",
    "BOBBY_MOORE", "BOBBY_CHARLTON",
    # Other greats
    "MARADONA", "DIEGO_MARADONA", "PELE", "CRUYFF", "JOHAN_CRUYFF", "ZIDANE",
    "ZINEDINE_ZIDANE", "ZIZOU", "BUFFON", "GIANLUIGI_BUFFON", "MALDINI",
    "PAOLO_MALDINI", "BARESI", "FRANCO_BARESI", "RONALDO_R9", "BATISTUTA",
    "GABRIEL_BATISTUTA", "ROMARIO", "GULLIT", "RUUD_GULLIT", "VAN_BASTEN",
    "MARCO_VAN_BASTEN", "PLATINI", "MICHEL_PLATINI", "BAGGIO", "ROBERTO_BAGGIO",
    "RIVALDO_BR", "DAVID_VILLA", "VILLA_ESP", "GERD_MULLER", "EUSEBIO_PT",
    "DI_STEFANO", "ALFREDO_DI_STEFANO", "PUSKAS_HUN", "GARRINCHA",
]

# ── Manager bench (extended) ───────────────────────────────────────────────

MANAGERS: list[str] = [
    # Current PL
    "GUARDIOLA", "PEP", "PEP_GUARDIOLA", "ARTETA", "MIKEL_ARTETA", "SLOT",
    "ARNE_SLOT", "AMORIM", "RUBEN_AMORIM", "POSTECOGLOU", "ANGE",
    "ANGE_POSTECOGLOU", "MARESCA", "ENZO_MARESCA", "HOWE", "EDDIE_HOWE",
    "EMERY", "UNAI_EMERY", "DYCHE", "SEAN_DYCHE", "MOYES", "DAVID_MOYES",
    "FRANK_BRENTFORD", "THOMAS_FRANK", "HURZELER", "FABIAN_HURZELER",
    "VAN_NISTELROOY_MGR", "GLASNER", "OLIVER_GLASNER", "MARCO_SILVA",
    "SILVA_FUL", "IRAOLA", "ANDONI_IRAOLA", "VIEIRA_GEN", "NUNO",
    "NUNO_ESPIRITO_SANTO", "NESS", "STEVE_COOPER", "HUGHES",
    "GARY_OLEARY",
    # Recent legends
    "FERGUSON", "FERGIE", "ALEX_FERGUSON", "WENGER", "ARSENE_WENGER",
    "MOURINHO", "JOSE_MOURINHO", "SPECIAL_ONE", "KLOPP", "JURGEN_KLOPP",
    "TUCHEL", "THOMAS_TUCHEL", "POCH", "POCHETTINO", "MAURICIO_POCHETTINO",
    "CONTE", "ANTONIO_CONTE", "ANCELOTTI", "CARLO_ANCELOTTI", "ALONSO_MGR",
    "XABI_ALONSO", "RANIERI", "CLAUDIO_RANIERI", "BENITEZ", "RAFA_BENITEZ",
    "ALLARDYCE", "SAM_ALLARDYCE", "BIG_SAM", "REDKNAPP_MGR", "HARRY_REDKNAPP",
    "PARDEW", "ALAN_PARDEW", "BRUCE_MGR", "STEVE_BRUCE", "PULIS",
    "TONY_PULIS", "MEGSON", "GARY_MEGSON", "CURBISHLEY", "ALAN_CURBISHLEY",
    "DI_MATTEO", "CHRIS_HUGHTON", "AVRAM_GRANT", "ADKINS", "NIGEL_ADKINS",
    # International / European managers
    "DESCHAMPS", "DIDIER_DESCHAMPS", "SOUTHGATE", "GARETH_SOUTHGATE",
    "HANSI_FLICK", "FLICK_DE", "JULIAN_NAGELSMANN", "NAGELSMANN", "DE_LA_FUENTE",
    "LUIS_DE_LA_FUENTE", "SCALONI", "LIONEL_SCALONI", "TUDOR", "IGOR_TUDOR",
    "INZAGHI", "SIMONE_INZAGHI", "CONCEICAO", "SERGIO_CONCEICAO", "MOTTA",
    "THIAGO_MOTTA", "RUDI_GARCIA", "DOMENICO_TEDESCO", "CHRISTOPHE_GALTIER",
    "ENRIQUE", "LUIS_ENRIQUE", "KOMPANY", "VINCENT_KOMPANY", "PROBIERZ",
    # British legend managers
    "SHANKLY", "BILL_SHANKLY", "PAISLEY", "BOB_PAISLEY", "REVIE", "DON_REVIE",
    "CLOUGH", "BRIAN_CLOUGH", "BRIAN_CLOUGH_SR", "GRAHAM_TAYLOR", "BOBBY_ROBSON",
    "TERRY_VENABLES", "VENABLES", "GLENN_HODDLE", "HODDLE", "KEEGAN_MGR",
    "KEVIN_KEEGAN",
]

# ── Pundits / commentators / presenters ────────────────────────────────────

PUNDITS: list[str] = [
    # Sky / TNT / BBC current
    "LINEKER", "GARY_LINEKER", "WRIGHT", "IAN_WRIGHT", "SHEARER_PUNDIT",
    "KEANE_ITV", "ROY_KEANE_PUNDIT", "CARRAGHER", "JAMIE_CARRAGHER",
    "NEVILLE", "GARY_NEVILLE", "PHIL_NEVILLE", "RIO_FERDINAND_PUNDIT",
    "FERDINAND_PUNDIT", "RICHARDS", "MICAH_RICHARDS", "MICAH", "SAVAGE",
    "ROBBIE_SAVAGE", "SOUNESS", "GRAEME_SOUNESS", "MERSON", "PAUL_MERSON",
    "REDKNAPP", "JAMIE_REDKNAPP", "SHARKEY", "OWEN_PUNDIT", "MICHAEL_OWEN_PUNDIT",
    "CRAIG_BURLEY", "MARK_LAWRENSON", "LAWRO", "ALAN_HANSEN", "HANSEN",
    "MARTIN_KEOWN", "KEOWN", "DION_DUBLIN", "DUBLIN", "JERMAINE_JENAS",
    "JENAS", "MATT_LE_TISSIER", "LE_TISSIER", "JEFF_STELLING", "STELLING",
    "CHRIS_KAMARA", "KAMMY",
    # Commentators
    "MARTIN_TYLER", "TYLER", "PETER_DRURY", "DRURY", "ALAN_PARRY",
    "CLIVE_TYLDESLEY", "TYLDESLEY", "JON_CHAMPION", "CHAMPION_COMM",
    "DARREN_FLETCHER", "DARRAGH_MAHER", "ROB_HAWTHORNE", "GUY_MOWBRAY",
    "JONATHAN_PEARCE", "STEVE_BOWER", "ALI_MAXWELL",
    # TalkSPORT / radio
    "JORDAN", "SIMON_JORDAN", "DURHAM", "ADRIAN_DURHAM", "JIM_WHITE",
    "DANNY_KELLY", "ANDY_GOLDSTEIN", "JASON_CUNDY", "PERRY_GROVES",
    # MOTD presenters / new gen
    "MOTD", "MARK_CHAPMAN", "CHAPMAN_MOTD", "GABBY_LOGAN", "GABBY",
    "ALEX_SCOTT_PUNDIT", "ALEX_SCOTT", "EILIDH_BARBOUR", "ELLEN_WHITE",
    "RACHEL_BROWN", "SUE_SMITH",
]


def all_extras() -> list[tuple[str, str]]:
    """Return (handle, category) pairs for everything in this module."""
    out: list[tuple[str, str]] = []
    for handles in PL_SQUADS.values():
        out.extend((h, "player") for h in handles)
    out.extend((h, "player") for h in CHAMP_PLAYERS)
    out.extend((h, "player") for h in SCOTTISH_PLAYERS)
    out.extend((h, "player") for h in EUROPEAN_STARS)
    out.extend((h, "player") for h in ICONS)
    out.extend((h, "manager") for h in MANAGERS)
    out.extend((h, "pundit") for h in PUNDITS)
    return out
