-- 0002_seed_teams.sql — 104 UK football clubs (PL + EFL Championship + L1 + L2 + SPL)
-- Brand colours sourced from official club colour references; primary = home shirt, secondary = trim/away

BEGIN;

INSERT INTO teams (slug, name, short_name, city, country, league, primary_color, secondary_color, founded_year) VALUES
-- ─── Premier League (20) ────────────────────────────────────────────────────
('arsenal',           'Arsenal',                       'Arsenal',     'London',         'GB-ENG', 'Premier League', '#EF0107', '#FFFFFF', 1886),
('aston-villa',       'Aston Villa',                   'Villa',       'Birmingham',     'GB-ENG', 'Premier League', '#670E36', '#94BEE5', 1874),
('bournemouth',       'AFC Bournemouth',               'Bournemouth', 'Bournemouth',    'GB-ENG', 'Premier League', '#DA291C', '#000000', 1899),
('brentford',         'Brentford',                     'Bees',        'London',         'GB-ENG', 'Premier League', '#E30613', '#FBB800', 1889),
('brighton',          'Brighton & Hove Albion',        'Brighton',    'Brighton',       'GB-ENG', 'Premier League', '#0057B8', '#FFCD00', 1901),
('chelsea',           'Chelsea',                       'Chelsea',     'London',         'GB-ENG', 'Premier League', '#034694', '#FFFFFF', 1905),
('crystal-palace',    'Crystal Palace',                'Palace',      'London',         'GB-ENG', 'Premier League', '#1B458F', '#C4122E', 1905),
('everton',           'Everton',                       'Toffees',     'Liverpool',      'GB-ENG', 'Premier League', '#003399', '#FFFFFF', 1878),
('fulham',            'Fulham',                        'Cottagers',   'London',         'GB-ENG', 'Premier League', '#FFFFFF', '#000000', 1879),
('ipswich',           'Ipswich Town',                  'Tractor Boys','Ipswich',        'GB-ENG', 'Premier League', '#3764A4', '#FFFFFF', 1878),
('leicester',         'Leicester City',                'Foxes',       'Leicester',      'GB-ENG', 'Premier League', '#003090', '#FDBE11', 1884),
('liverpool',         'Liverpool',                     'Reds',        'Liverpool',      'GB-ENG', 'Premier League', '#C8102E', '#00B2A9', 1892),
('man-city',          'Manchester City',               'City',        'Manchester',     'GB-ENG', 'Premier League', '#6CABDD', '#1C2C5B', 1880),
('man-utd',           'Manchester United',             'United',      'Manchester',     'GB-ENG', 'Premier League', '#DA291C', '#FBE122', 1878),
('newcastle',         'Newcastle United',              'Magpies',     'Newcastle',      'GB-ENG', 'Premier League', '#241F20', '#FFFFFF', 1892),
('nottm-forest',      'Nottingham Forest',             'Forest',      'Nottingham',     'GB-ENG', 'Premier League', '#DD0000', '#FFFFFF', 1865),
('southampton',       'Southampton',                   'Saints',      'Southampton',    'GB-ENG', 'Premier League', '#D71920', '#FFFFFF', 1885),
('spurs',             'Tottenham Hotspur',             'Spurs',       'London',         'GB-ENG', 'Premier League', '#132257', '#FFFFFF', 1882),
('west-ham',          'West Ham United',               'Hammers',     'London',         'GB-ENG', 'Premier League', '#7A263A', '#1BB1E7', 1895),
('wolves',            'Wolverhampton Wanderers',       'Wolves',      'Wolverhampton',  'GB-ENG', 'Premier League', '#FDB913', '#231F20', 1877),

-- ─── Championship (24) ──────────────────────────────────────────────────────
('blackburn',         'Blackburn Rovers',              'Rovers',      'Blackburn',      'GB-ENG', 'Championship',   '#009EE0', '#FFFFFF', 1875),
('bristol-city',      'Bristol City',                  'Robins',      'Bristol',        'GB-ENG', 'Championship',   '#E21C38', '#FFFFFF', 1894),
('burnley',           'Burnley',                       'Clarets',     'Burnley',        'GB-ENG', 'Championship',   '#6C1D45', '#99D6EA', 1882),
('cardiff',           'Cardiff City',                  'Bluebirds',   'Cardiff',        'GB-WLS', 'Championship',   '#0070B5', '#D11524', 1899),
('coventry',          'Coventry City',                 'Sky Blues',   'Coventry',       'GB-ENG', 'Championship',   '#87CEEB', '#000000', 1883),
('derby',             'Derby County',                  'Rams',        'Derby',          'GB-ENG', 'Championship',   '#FFFFFF', '#000000', 1884),
('hull',              'Hull City',                     'Tigers',      'Kingston-upon-Hull','GB-ENG','Championship', '#F18A01', '#000000', 1904),
('leeds',             'Leeds United',                  'Whites',      'Leeds',          'GB-ENG', 'Championship',   '#FFCD00', '#1D4189', 1919),
('luton',             'Luton Town',                    'Hatters',     'Luton',          'GB-ENG', 'Championship',   '#F78F1E', '#1B449C', 1885),
('middlesbrough',     'Middlesbrough',                 'Boro',        'Middlesbrough',  'GB-ENG', 'Championship',   '#E21C38', '#FFFFFF', 1876),
('millwall',          'Millwall',                      'Lions',       'London',         'GB-ENG', 'Championship',   '#001D58', '#FFFFFF', 1885),
('norwich',           'Norwich City',                  'Canaries',    'Norwich',        'GB-ENG', 'Championship',   '#FFF200', '#00A650', 1902),
('oxford',            'Oxford United',                 'U''s',        'Oxford',         'GB-ENG', 'Championship',   '#FFE100', '#003E7E', 1893),
('plymouth',          'Plymouth Argyle',               'Pilgrims',    'Plymouth',       'GB-ENG', 'Championship',   '#005842', '#F4F4F4', 1886),
('portsmouth',        'Portsmouth',                    'Pompey',      'Portsmouth',     'GB-ENG', 'Championship',   '#001489', '#FFFFFF', 1898),
('preston',           'Preston North End',             'Lilywhites',  'Preston',        'GB-ENG', 'Championship',   '#FFFFFF', '#1B458F', 1880),
('qpr',               'Queens Park Rangers',           'QPR',         'London',         'GB-ENG', 'Championship',   '#1D5BA4', '#FFFFFF', 1882),
('sheff-utd',         'Sheffield United',              'Blades',      'Sheffield',      'GB-ENG', 'Championship',   '#EE2737', '#000000', 1889),
('sheff-wed',         'Sheffield Wednesday',           'Owls',        'Sheffield',      'GB-ENG', 'Championship',   '#0E1F58', '#FFFFFF', 1867),
('stoke',             'Stoke City',                    'Potters',     'Stoke-on-Trent', 'GB-ENG', 'Championship',   '#E03A3E', '#FFFFFF', 1863),
('sunderland',        'Sunderland',                    'Black Cats',  'Sunderland',     'GB-ENG', 'Championship',   '#EB172B', '#FFFFFF', 1879),
('swansea',           'Swansea City',                  'Swans',       'Swansea',        'GB-WLS', 'Championship',   '#FFFFFF', '#000000', 1912),
('watford',           'Watford',                       'Hornets',     'Watford',        'GB-ENG', 'Championship',   '#FBEE23', '#ED2127', 1881),
('wba',               'West Bromwich Albion',          'Baggies',     'West Bromwich',  'GB-ENG', 'Championship',   '#122F67', '#FFFFFF', 1878),

-- ─── League One (24) ────────────────────────────────────────────────────────
('barnsley',          'Barnsley',                      'Tykes',       'Barnsley',       'GB-ENG', 'League One',     '#E2231A', '#FFFFFF', 1887),
('birmingham',        'Birmingham City',               'Blues',       'Birmingham',     'GB-ENG', 'League One',     '#0000B7', '#FFFFFF', 1875),
('blackpool',         'Blackpool',                     'Tangerines',  'Blackpool',      'GB-ENG', 'League One',     '#F68712', '#FFFFFF', 1887),
('bolton',            'Bolton Wanderers',              'Trotters',    'Bolton',         'GB-ENG', 'League One',     '#FFFFFF', '#26408B', 1874),
('bristol-rovers',    'Bristol Rovers',                'Gas',         'Bristol',        'GB-ENG', 'League One',     '#003875', '#FFFFFF', 1883),
('burton',            'Burton Albion',                 'Brewers',     'Burton-upon-Trent','GB-ENG','League One',    '#FFE500', '#000000', 1950),
('cambridge',         'Cambridge United',              'U''s',        'Cambridge',      'GB-ENG', 'League One',     '#FFCC33', '#000000', 1912),
('charlton',          'Charlton Athletic',             'Addicks',     'London',         'GB-ENG', 'League One',     '#E31B23', '#FFFFFF', 1905),
('crawley',           'Crawley Town',                  'Reds',        'Crawley',        'GB-ENG', 'League One',     '#E11820', '#FFFFFF', 1896),
('exeter',            'Exeter City',                   'Grecians',    'Exeter',         'GB-ENG', 'League One',     '#E60000', '#FFFFFF', 1904),
('huddersfield',      'Huddersfield Town',             'Terriers',    'Huddersfield',   'GB-ENG', 'League One',     '#0E63AD', '#FFFFFF', 1908),
('leyton-orient',     'Leyton Orient',                 'O''s',        'London',         'GB-ENG', 'League One',     '#E2231A', '#FFFFFF', 1881),
('lincoln',           'Lincoln City',                  'Imps',        'Lincoln',        'GB-ENG', 'League One',     '#E11820', '#FFFFFF', 1884),
('mansfield',         'Mansfield Town',                'Stags',       'Mansfield',      'GB-ENG', 'League One',     '#FFD700', '#1B4A91', 1897),
('northampton',       'Northampton Town',              'Cobblers',    'Northampton',    'GB-ENG', 'League One',     '#841B2D', '#FFD700', 1897),
('peterborough',      'Peterborough United',           'Posh',        'Peterborough',   'GB-ENG', 'League One',     '#0078D4', '#FFFFFF', 1934),
('reading',           'Reading',                       'Royals',      'Reading',        'GB-ENG', 'League One',     '#004494', '#FFFFFF', 1871),
('rotherham',         'Rotherham United',              'Millers',     'Rotherham',      'GB-ENG', 'League One',     '#E11820', '#FFFFFF', 1925),
('shrewsbury',        'Shrewsbury Town',               'Shrews',      'Shrewsbury',     'GB-ENG', 'League One',     '#003875', '#FFD700', 1886),
('stevenage',         'Stevenage',                     'Boro',        'Stevenage',      'GB-ENG', 'League One',     '#E11820', '#FFFFFF', 1976),
('stockport',         'Stockport County',              'Hatters',     'Stockport',      'GB-ENG', 'League One',     '#003875', '#FFFFFF', 1883),
('wigan',             'Wigan Athletic',                'Latics',      'Wigan',          'GB-ENG', 'League One',     '#0000FF', '#FFFFFF', 1932),
('wrexham',           'Wrexham',                       'Red Dragons', 'Wrexham',        'GB-WLS', 'League One',     '#E2231A', '#FFFFFF', 1864),
('wycombe',           'Wycombe Wanderers',             'Chairboys',   'High Wycombe',   'GB-ENG', 'League One',     '#003875', '#87CEEB', 1887),

-- ─── League Two (24) ────────────────────────────────────────────────────────
('accrington',        'Accrington Stanley',            'Stanley',     'Accrington',     'GB-ENG', 'League Two',     '#E11820', '#FFFFFF', 1968),
('barrow',            'Barrow',                        'Bluebirds',   'Barrow-in-Furness','GB-ENG','League Two',    '#0078D4', '#FFFFFF', 1901),
('bradford',          'Bradford City',                 'Bantams',     'Bradford',       'GB-ENG', 'League Two',     '#841B2D', '#FFCC00', 1903),
('bromley',           'Bromley',                       'Ravens',      'Bromley',        'GB-ENG', 'League Two',     '#FFFFFF', '#000000', 1892),
('carlisle',          'Carlisle United',               'Cumbrians',   'Carlisle',       'GB-ENG', 'League Two',     '#003875', '#FFFFFF', 1904),
('cheltenham',        'Cheltenham Town',               'Robins',      'Cheltenham',     'GB-ENG', 'League Two',     '#E11820', '#FFFFFF', 1887),
('chesterfield',      'Chesterfield',                  'Spireites',   'Chesterfield',   'GB-ENG', 'League Two',     '#0070B5', '#FFFFFF', 1867),
('colchester',        'Colchester United',             'U''s',        'Colchester',     'GB-ENG', 'League Two',     '#003875', '#FFFFFF', 1937),
('crewe',             'Crewe Alexandra',               'Railwaymen',  'Crewe',          'GB-ENG', 'League Two',     '#E11820', '#FFFFFF', 1877),
('doncaster',         'Doncaster Rovers',              'Rovers',      'Doncaster',      'GB-ENG', 'League Two',     '#E11820', '#FFFFFF', 1879),
('fleetwood',         'Fleetwood Town',                'Cod Army',    'Fleetwood',      'GB-ENG', 'League Two',     '#E11820', '#FFFFFF', 1908),
('gillingham',        'Gillingham',                    'Gills',       'Gillingham',     'GB-ENG', 'League Two',     '#0078D4', '#FFFFFF', 1893),
('grimsby',           'Grimsby Town',                  'Mariners',    'Grimsby',        'GB-ENG', 'League Two',     '#000000', '#FFFFFF', 1878),
('harrogate',         'Harrogate Town',                'Sulphurites', 'Harrogate',      'GB-ENG', 'League Two',     '#FFD700', '#000000', 1914),
('mk-dons',           'Milton Keynes Dons',            'Dons',        'Milton Keynes',  'GB-ENG', 'League Two',     '#FFFFFF', '#0078D4', 2004),
('morecambe',         'Morecambe',                     'Shrimps',     'Morecambe',      'GB-ENG', 'League Two',     '#E11820', '#FFFFFF', 1920),
('newport',           'Newport County',                'Exiles',      'Newport',        'GB-WLS', 'League Two',     '#FFD700', '#000000', 1912),
('notts-county',      'Notts County',                  'Magpies',     'Nottingham',     'GB-ENG', 'League Two',     '#000000', '#FFFFFF', 1862),
('port-vale',         'Port Vale',                     'Valiants',    'Stoke-on-Trent', 'GB-ENG', 'League Two',     '#FFFFFF', '#000000', 1876),
('salford',           'Salford City',                  'Ammies',      'Salford',        'GB-ENG', 'League Two',     '#E11820', '#FFFFFF', 1940),
('swindon',           'Swindon Town',                  'Robins',      'Swindon',        'GB-ENG', 'League Two',     '#E11820', '#FFFFFF', 1879),
('tranmere',          'Tranmere Rovers',               'Rovers',      'Birkenhead',     'GB-ENG', 'League Two',     '#003875', '#FFFFFF', 1884),
('walsall',           'Walsall',                       'Saddlers',    'Walsall',        'GB-ENG', 'League Two',     '#E11820', '#FFFFFF', 1888),
('afc-wimbledon',     'AFC Wimbledon',                 'Dons',        'London',         'GB-ENG', 'League Two',     '#003875', '#FFFFFF', 2002),

-- ─── Scottish Premiership (12) ──────────────────────────────────────────────
('aberdeen',          'Aberdeen',                      'Dons',        'Aberdeen',       'GB-SCT', 'Scottish Premiership', '#E2231A', '#FFFFFF', 1903),
('celtic',            'Celtic',                        'Celtic',      'Glasgow',        'GB-SCT', 'Scottish Premiership', '#018749', '#FFFFFF', 1887),
('dundee',            'Dundee',                        'Dee',         'Dundee',         'GB-SCT', 'Scottish Premiership', '#0066CC', '#FFFFFF', 1893),
('dundee-utd',        'Dundee United',                 'Tangerines',  'Dundee',         'GB-SCT', 'Scottish Premiership', '#F37021', '#000000', 1909),
('hearts',            'Heart of Midlothian',           'Hearts',      'Edinburgh',      'GB-SCT', 'Scottish Premiership', '#7C2128', '#FFFFFF', 1874),
('hibs',              'Hibernian',                     'Hibs',        'Edinburgh',      'GB-SCT', 'Scottish Premiership', '#005000', '#FFFFFF', 1875),
('kilmarnock',        'Kilmarnock',                    'Killie',      'Kilmarnock',     'GB-SCT', 'Scottish Premiership', '#003090', '#FFFFFF', 1869),
('motherwell',        'Motherwell',                    'Steelmen',    'Motherwell',     'GB-SCT', 'Scottish Premiership', '#FFCD00', '#7C2128', 1886),
('rangers',           'Rangers',                       'Gers',        'Glasgow',        'GB-SCT', 'Scottish Premiership', '#1B458F', '#FFFFFF', 1872),
('ross-county',       'Ross County',                   'Staggies',    'Dingwall',       'GB-SCT', 'Scottish Premiership', '#003090', '#E2231A', 1929),
('st-johnstone',      'St Johnstone',                  'Saints',      'Perth',          'GB-SCT', 'Scottish Premiership', '#003090', '#FFFFFF', 1884),
('st-mirren',         'St Mirren',                     'Buddies',     'Paisley',        'GB-SCT', 'Scottish Premiership', '#000000', '#FFFFFF', 1877);

COMMIT;
